[package]
name = "ldns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitreader = { path = "./libs/bitreader" }
rand = { path="./libs/rand" }
